version: '2'
services:
  jenkins:
    image: jenkinsfinal
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50003:50000
    networks:
      internship_default:
        ipv4_address: 172.18.0.3
    volumes:
      - /home/ghassen/Documents/Internship/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
  nexus:
    image: sonatype/nexus3:3.38.0
    container_name: nexus
    privileged: true
    user: root
    volumes:
      - /home/ghassen/Documents/Internship/nexus-data:/nexus-data
    ports:
      - 8081:8081
      - 8085:8085 
    networks:
      internship_default:
        ipv4_address: 172.18.0.4
  sonarqube:
    image: sonarqube:9.3.0-community
    container_name: sonarqube
    privileged: true
    user: root
    volumes:
      - /home/ghassen/Documents/Internship/sonarqube_data:/opt/sonarqube/data
      - /home/ghassen/Documents/Internship/sonarqube_extensions:/opt/sonarqube/extensions
      - /home/ghassen/Documents/Internship/sonarqube_logs:/opt/sonarqube/logs
    ports:
      - 9000:9000
    networks:
      internship_default:
        ipv4_address: 172.18.0.5
  gitlab:
    image: 'gitlab/gitlab-ce:14.7.6-ce.0'
    container_name: gitlab
    privileged: true
    user: root
    environment:
      GITLAB_OMNIBUS_CONFIG: 
        external_url 'http://localhost'
    ports:
      - 80:80
      - 443:443
    networks:
      internship_default:
        ipv4_address: 172.18.0.2
    volumes:
      - /home/ghassen/Documents/Internship/gitlab/config:/etc/gitlab
      - /home/ghassen/Documents/Internship/gitlab/logs:/var/log/gitlab
      - /home/ghassen/Documents/Internship/gitlab/data:/var/opt/gitlab
volumes:
  nexus-data: {}
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
networks:
    internship_default:
        driver: bridge
        ipam:
            config:
                - subnet: "172.18.0.0/16"
